modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="moretools"
version="1.0.0"
displayName="MoreTools+"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="vasil, MCreator"

[[dependencies.moretools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




